### ISSUE TITLE
EPUB: Not able to render EpubNavigatorFragment in release mode

### ISSUE THREAD

**Issue by 838** [readium/kotlin-toolkit#295]
### What happened?
On Debug mode or version 2.2.1 everything works as expected, but when I run our app in release mode by develop branch I'm no longer able to create a `EpubNavigatorFragment`.

### Environment

* Readium version: latest develop

#### Development environment

* OS: macOS 13.0  
* IDE: vscode 

#### Testing device

* Android version: 12.0
* Model: Galaxy A33 5G 
* Is it an emulator? No

### Additional context

* Are you willing to fix the problem and contribute a pull request? Yes 

```log
PlatformException: PlatformException(error, c
Mark the class as @Serializable or provide the serializer explicitly., null, )
  File "message_codecs.dart", line 653, in StandardMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 296, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "platform_views.dart", line 1146, in TextureAndroidViewController._sendCreateMessage
  File "<asynchronous suspension>"
  File "platform_views.dart", line 792, in AndroidViewController.create
g: Serializer for class 'd' is not found.
    at
    at kd.o1.d(Platform.common.kt:3)
    at kd.n1.m(Unknown Source:5)
    at gd.k.f(Serializers.kt:2)
    at gd.j.c(Unknown Source:0)
    at gd.k.e(Unknown Source:9)
    at gd.j.b(Unknown Source:0)
    at xe.c$b$a.w(EpubSettings.kt:8)
    at xe.c$b$a.x(EpubSettings.kt:2)
    at xe.c$b.<init>(EpubSettings.kt:2)
    at xe.c$b$a.H(Unknown Source:89)
    at xe.c$b$a.I(EpubSettings.kt:6)
    at xe.b.<init>(EpubNavigatorViewModel.kt:15)
    at xe.b$a$a.a(ViewModelFactory.kt:5)
    at androidx.lifecycle.a1.b(Unknown Source:10)
    at xe.b$a$a.b(Unknown Source:0)
    at androidx.lifecycle.z0.b(ViewModelProvider.kt:7)
    at androidx.lifecycle.z0.a(ViewModelProvider.kt:2)
    at androidx.lifecycle.y0.b(ViewModelLazy.kt:7)
    at androidx.lifecycle.y0.getValue(Unknown Source:0)
    at org.readium.r2.navigator.epub.EpubNavigatorFragment.P2(Unknown Source:2)
    at org.readium.r2.navigator.epub.EpubNavigatorFragment.N0(EpubNavigatorFragment.kt:30)
    at androidx.fragment.app.Fragment.q1(Fragment.java:4)
    at androidx.fragment.app.d0.f(FragmentStateManager.java:17)
    at androidx.fragment.app.d0.m(FragmentStateManager.java:20)
    at androidx.fragment.app.w.e0(FragmentManager.java:31)
    at androidx.fragment.app.w.i1(FragmentManager.java:9)
    at androidx.fragment.app.w.c0(FragmentManager.java:5)
    at androidx.fragment.app.a.h(BackStackRecord.java:2)
    at dk.nota.flutter_readium.a.f(EpubNavigatorView.kt:4)
    at dk.nota.flutter_readium.a.onAttachedToWindow(EpubNavigatorView.kt:3)
    at android.view.View.dispatchAttachedToWindow(View.java:21976)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4293)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4302)
    at android.view.ViewGroup.addViewInner(ViewGroup.java:6127)
    at android.view.ViewGroup.addView(ViewGroup.java:5903)
    at android.view.ViewGroup.addView(ViewGroup.java:5843)
    at android.view.ViewGroup.addView(ViewGroup.java:5815)
    at io.flutter.plugin.platform.o$a.d(PlatformViewsController.java:53)
    at y8.k$a.c(PlatformViewsChannel.java:19)
    at y8.k$a.onMethodCall(PlatformViewsChannel.java:12)
    at z8.k$a.a(MethodChannel.java:2)
    at n8.c.l(DartMessenger.java:2)
    at n8.c.m(DartMessenger.java:2)
    at n8.c.h(Unknown Source:0)
    at n8.b.run(Unknown Source:12)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8751)
    at java.lang.reflect.Method.invoke
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    at
```

**Comment by mickael-menu** [comment]
If you get this issue only in release mode, it could be because of Proguard. Could you follow the instructions from kotlinx-serialization regarding Proguard and see if it helps? https://github.com/Kotlin/kotlinx.serialization#android

**Comment by stevenzeck** [comment]
Also, Flutter isn't officially supported.

**Comment by 838** [comment]
@mickael-menu Thank you so much for your help, that was because of Proguard,  but weird that we didn't had the issue in older versions

**Comment by mickael-menu** [comment]
In the last released version, Readium didn't use `kotlinx-serialization`.

**Comment by mickael-menu** [comment]
@vishalbaps Mantano is working on a Flutter/Dart port of the Readium toolkit, you can check it out here https://github.com/Mantano/iridium
