### ISSUE TITLE
Error: org.readium.r2.shared.fetcher.Resource$Exception$NotFound: java.lang.Exception:

### ISSUE THREAD

**Issue by ajay9889** [readium/kotlin-toolkit#297]
## Bug Report

we are really stuck after migrated the readium with new version.. In QA team.. they are found one of the book is not getting open in Android but the iOS version is working fine... Please refer the log below.

The book name: Mustard: Sowing seeds of Fun and Faith Vol 14. Issue 1
It's paid book
+ iOS works fine (attached video demo)
+ Android is incorrect (attached video demo)
Readium version on Android
+ val READIUM_VERSION = "2.2.0"
+ readium:liblcp:2.0.5
The log:
2022-11-04 17:17:00.086 24292-25354/com.education.comic.ebook E/PublicationResourceHandler$get: org.readium.r2.shared.fetcher.Resource$Exception$NotFound: java.lang.Exception: No file entry at path OEBPS/fonts/g_font_10.ttf?reload=1664860278828.
        at org.readium.r2.shared.fetcher.ArchiveFetcher$EntryResource.entry(ArchiveFetcher.kt:63)
        at org.readium.r2.shared.fetcher.ArchiveFetcher$EntryResource.link(ArchiveFetcher.kt:71)
        at org.readium.r2.lcp.LcpDecryptor$transform$1.invokeSuspend(LcpDecryptor.kt:36)
        at org.readium.r2.lcp.LcpDecryptor$transform$1.invoke(Unknown Source:8)
        at org.readium.r2.lcp.LcpDecryptor$transform$1.invoke(Unknown Source:2)
        at org.readium.r2.shared.fetcher.LazyResource.resource(Resource.kt:329)
        at org.readium.r2.shared.fetcher.LazyResource.link(Resource.kt:334)
        at org.readium.r2.shared.fetcher.ProxyResource.link$suspendImpl(Resource.kt:207)
        at org.readium.r2.shared.fetcher.ProxyResource.link(Unknown Source:0)
        at org.readium.r2.streamer.fetcher.HtmlInjector$transform$1.invokeSuspend(HtmlInjector.kt:35)
        at org.readium.r2.streamer.fetcher.HtmlInjector$transform$1.invoke(Unknown Source:8)
        at org.readium.r2.streamer.fetcher.HtmlInjector$transform$1.invoke(Unknown Source:2)
        at org.readium.r2.shared.fetcher.LazyResource.resource(Resource.kt:329)
        at org.readium.r2.shared.fetcher.LazyResource.link(Resource.kt:334)
        at org.readium.r2.streamer.server.handler.PublicationResourceHandler.serveResponse(PublicationResourceHandler.kt:79)
        at org.readium.r2.streamer.server.handler.PublicationResourceHandler.access$serveResponse(PublicationResourceHandler.kt:30)
        at org.readium.r2.streamer.server.handler.PublicationResourceHandler$get$1.invokeSuspend(PublicationResourceHandler.kt:54)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at org.readium.r2.streamer.server.handler.PublicationResourceHandler.get(PublicationResourceHandler.kt:45)
        at org.nanohttpd.router.RouterNanoHTTPD$UriResource.process(RouterNanoHTTPD.java:385)
        at org.nanohttpd.router.RouterNanoHTTPD$UriRouter.process(RouterNanoHTTPD.java:597)
        at org.nanohttpd.router.RouterNanoHTTPD.serve(RouterNanoHTTPD.java:672)
        at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:376)
        at org.nanohttpd.protocols.http.NanoHTTPD$1.handle(NanoHTTPD.java:372)
        at org.nanohttpd.protocols.http.NanoHTTPD.handle(NanoHTTPD.java:535)
        at org.nanohttpd.protocols.http.HTTPSession.execute(HTTPSession.java:418)
        at org.nanohttpd.protocols.http.ClientHandler.run(ClientHandler.java:75)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Exception: No file entry at path OEBPS/fonts/g_font_10.ttf?reload=1664860278828.
        at org.readium.r2.shared.util.archive.JavaZip.entry(JavaZip.kt:91)
ios recorded video of working fine. Android showign error..?

### What happened?

Books open and then showing error
### How to reproduce?

In Android

### Environment

* Readium version:

#### Development environment

* OS: Android Mobile 

https://user-images.githubusercontent.com/9216373/200786076-b65fa501-d587-4dc6-967e-22356dc4751e.mp4
iOS working App 👍 
https://user-images.githubusercontent.com/9216373/200786123-3f218f52-21a5-4ff3-9600-9668a44812e2.mp4

#### Testing device

* Android version:
* Model: ANy
* Is it an emulator? Yes or No

### Additional context

* Are you willing to fix the problem and contribute a pull request? Yes or No

**Comment by ajay9889** [comment]
@mickael-menu , please review thanks

**Comment by mickael-menu** [comment]
Note to self: `Mustard_ Sowing Seeds of Fun and Faith Vol - Shepherds Voice.epub`

**Comment by mickael-menu** [comment]
I can't reproduce the issue from `develop` or the last released version with the sample. Do you have an LCP-protected version to share?

**Comment by ajay9889** [comment]
@mickael-menu  the same book we also tried it works but the .LCP file is not working... Please find the link of LCP file which i have pasted on the slack channel. iOS is getting load, the font issue will be

**Comment by mickael-menu** [comment]
Still no issue for me with the LCP protected file.


https://user-images.githubusercontent.com/58686775/202688324-24f4b2e7-48e4-4ec2-b5ed-d764708d5c71.mov

**Comment by ajay9889** [comment]
@mickael-menu I am facing this issue on "Android" on in iOS. Please check on Android device please.
